### ISSUE TITLE
[BUG] Randomly tries to calculate stuff

### ISSUE THREAD

**Issue by NextRaven10** [Emirlol/chatcalc#10]
An example:
![grafik](https://github.com/user-attachments/assets/55d646a6-488a-42ac-8c20-1378f718b26f)

Idk what it is doing but I don´t think it is intented and if it is it should be toggleable

**Comment by Emirlol** [comment]
This is intended behaviour, allowing you to multiply different variables and constants when they are connected without a `*`. This is allowed because `3x=9` is more intuitive from a maths perspective even if `3*x=9` is more *correct*. Both of these are considered valid syntax. A similar thing goes for exponents, while z^3 is more concise, x*x*x and therefore xxx is still valid (though a bit of a stretch).

As for why this happens on `z`, `x`, `y` and `z` are constants defined by chatcalc that are substituted with you `x` `y` `z` position in the world.
So `zzz` is basically your `z` position cubed.

If you don't want the pop up I think you can do `display_above=false` and press tab in chat to disable it. You can still tab to replace the results of equations or complete equations with the resulting values if the equations end with a `=`, so you're not disabling the mod completely.
